# Uso opcional desde CLI: liquibase update (antes exporta LIQUIBASE_COMMAND_PASSWORD)
changeLogFile: db/changelog/db.changelog-master.yaml
searchPath: .
url: jdbc:sqlserver://localhost:1434;databaseName=lavado_vehicular;encrypt=true;trustServerCertificate=true
username: sa
databaseChangeLogTableName: DATABASECHANGELOG_PAYMENT
databaseChangeLogLockTableName: DATABASECHANGELOGLOCK_PAYMENT
